### PR TITLE
Update spec for due diligence

### PR DESCRIPTION
**Pull request by mouhajer-ch**
Update spec for due diligence

Resolves [ROE-1249](https://companieshouse.atlassian.net/browse/ROE-1249)

### CODE REVIEW

**Comment by mwestacott** [comment]
Just one general thought on this @mouhajer-ch related to what I said at stand-up - does this spec change need something to specify what countries are acceptable? Due Diligence screens accept England, Scotland, Wales or Ireland only for address countries...

**Comment by mouhajer-ch** [comment]
> Just one general thought on this @mouhajer-ch related to what I said at stand-up - does this spec change need something to specify what countries are acceptable? Due Diligence screens accept England, Scotland, Wales or Ireland only for address countries...

Hi @mwestacott, has already been considered in the following commit https://github.com/companieshouse/overseas-entities-api/commit/7d182c52c2299635a87214a70d836d9ea62a645d on PR https://github.com/companieshouse/overseas-entities-api/pull/85 with the `anyOf` tag, that validates the value against any (one or more) of the subschemas. For more info [here](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/)

**Comment by mwestacott** [comment]
> here

Thanks. Is it possible to validate against sub-schemas for specific fields on specific screens, since at the moment the spec seems to suggest that any of these countries are acceptable on all the screens?

**Comment by mouhajer-ch** [comment]
> > Just one general thought on this @mouhajer-ch related to what I said at stand-up - does this spec change need something to specify what countries are acceptable? Due Diligence screens accept England, Scotland, Wales or Ireland only for address countries...
> 
> > Hi @mwestacott, has already been considered in the following commit [7d182c5](https://github.com/companieshouse/overseas-entities-api/commit/7d182c52c2299635a87214a70d836d9ea62a645d) on PR #85 with the anyOf tag, that validates the value against any (one or more) of the subschemas. For more info [here](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/)
> 
> Thanks. Is it possible to validate against sub-schemas for specific fields on specific screens, since at the moment the spec seems to suggest that any of these countries are acceptable on all the screens?

It is what it does, we can have a call :)

**Review by mwestacott — APPROVED** [review]

**Pull request merged**
